### ISSUE TITLE
求助，发布组件报错！

### ISSUE THREAD

**Issue by swanky2009** [ymm-tech/gods-pen-cli#5]
我写了一个组件，用组件预览工具运行正常，但是发布以后，引入到项目中报错。
错误信息如下：
TypeError: r is undefined
Unhandled promise rejection 
TypeError: n is undefined
Stack trace:
e/<@http://editor.weilaikejiyun.com/editor/static/js/index.facd03b5.js:1:139261
l@http://editor.weilaikejiyun.com/editor/static/js/chunk-vendors.5667f90f.js:16:128333
x/<@http://editor.weilaikejiyun.com/editor/static/js/chunk-vendors.5667f90f.js:16:129673
w/</e[t]@http://editor.weilaikejiyun.com/editor/static/js/chunk-vendors.5667f90f.js:16:128753
Mn@http://editor.weilaikejiyun.com/editor/static/js/index.facd03b5.js:1:134434
r@http://editor.weilaikejiyun.com/editor/static/js/index.facd03b5.js:1:134642
u@http://editor.weilaikejiyun.com/editor/babel-polyfill.v6_20_0.min.js:2:26885
I/<@http://editor.weilaikejiyun.com/editor/babel-polyfill.v6_20_0.min.js:2:27007
a@http://editor.weilaikejiyun.com/editor/babel-polyfill.v6_20_0.min.js:1:18228
babel-polyfill.v6_20_0.min.js:2:27238
LinkError: import object field 'tableBase' is not a Number

**Comment by swanky2009** [comment]
调试发现加载组件报错
TypeError: Cannot read property 'default' of undefined
    at eval (componentLoader.js?2197:26)

**Comment by mingyuanwei** [comment]
尝试注册了你部署的服务，似乎由于ng配置问题，出现无限重定向，不能访问到编辑器页面，因此无法查看具体问题。或许你可以到官方钉钉群或者微信群中联系开发者。

**Comment by swanky2009** [comment]
@mingyuanwei 能否开源一个完整的组件例子呢？
